-- Create Brands table
CREATE TABLE IF NOT EXISTS public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

-- Create policies (Idempotent)
DROP POLICY IF EXISTS "Allow public read-only access" ON public.brands;
CREATE POLICY "Allow public read-only access" ON public.brands
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin full access" ON public.brands;
CREATE POLICY "Allow admin full access" ON public.brands
    FOR ALL USING (auth.role() = 'authenticated');
