-- Create Products table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_ar TEXT,
    price_egp NUMERIC,
    category TEXT,
    brand_id BIGINT REFERENCES public.brands(id),
    origin TEXT, -- 'Imported' or 'Egyptian Agency'
    is_imported BOOLEAN DEFAULT true,
    is_spotlight BOOLEAN DEFAULT false,
    is_upon_request BOOLEAN DEFAULT false,
    is_sold_out BOOLEAN DEFAULT false,
    description TEXT,
    description_ar TEXT,
    mileage TEXT,
    fuel_type TEXT,
    transmission TEXT,
    version TEXT,
    image_url TEXT,
    gallery TEXT[], -- Array of image URLs
    diagnostics_url TEXT,
    color TEXT,
    color_ar TEXT,
    order_explore INTEGER DEFAULT 0,
    order_spotlight INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public read-only access" ON public.products
    FOR SELECT USING (true);

CREATE POLICY "Allow admin full access" ON public.products
    FOR ALL USING (auth.role() = 'authenticated');
